apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: calibre-book-db
  name: calibre-book-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  nfs:
    server: 192.168.2.14
    path: /default/docker/Calibre
